# Entrambi: strategy_bits=8 + chance_bits=8
[ranges]
oop = "66+,A8s+,A5s-A4s,AJo+,K9s+,KQo,QTs+,JTs,96s+,85s+,75s+,65s,54s"
ip = "QQ-22,AQs-A2s,ATo+,K5s+,KJo+,Q8s+,J8s+,T7s+,96s+,86s+,75s+,64s+,53s+"

[cards]
flop = "Td9d6h"
turn = "Qc"
river = ""

[tree]
starting_pot = 200
effective_stack = 900

[bet_sizes.flop]
oop_bet = "60%, e, a"
oop_raise = "2.5x"
ip_bet = "60%, e, a"
ip_raise = "2.5x"

[bet_sizes.turn]
oop_bet = "60%, e, a"
oop_raise = "2.5x"
ip_bet = "60%, e, a"
ip_raise = "2.5x"

[bet_sizes.river]
oop_bet = "60%, e, a"
oop_raise = "2.5x"
ip_bet = "60%, e, a"
ip_raise = "2.5x"

[solver]
max_iterations = 10
target_exploitability_pct = 10.0
quantization = "16bit"
strategy_bits = 8
chance_bits = 8
dry_run = false

[output]
directory = "test_output"

